/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

/**
 *
 * @author hp
 */
public class NewAC extends javax.swing.JFrame {

    /**
     * Creates new form NewAC
     */
    
    
    int newac_day, newac_year;
    String newac_month, newac_installed_by, newac_brand, newac_block, newac_floor, newac_room, newac_date;
    
    
    
    
    
    public NewAC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t_newac_day = new javax.swing.JTextField();
        c_newac_month = new javax.swing.JComboBox<>();
        t_newac_year = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_newac_installedby = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_newac_brand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_newac_block = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_newac_floor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_newac_room = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b_newac_submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Installation Date:");

        t_newac_day.setText("Day");
        t_newac_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_newac_dayActionPerformed(evt);
            }
        });

        c_newac_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        t_newac_year.setText("Year");

        jLabel2.setText("Installed By:");

        t_newac_installedby.setText("Enter Name");

        jLabel3.setText("Brand:");

        t_newac_brand.setText("Enter Brand Name");
        t_newac_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_newac_brandActionPerformed(evt);
            }
        });

        jLabel4.setText("Block:");

        t_newac_block.setText("Enter Block");

        jLabel5.setText("Floor:");

        t_newac_floor.setText("Enter Floor");

        jLabel6.setText("Room Number:");

        t_newac_room.setText("Enter Room Number");

        jLabel7.setText("ID:");

        jLabel8.setText("Auto Generated");

        b_newac_submit.setText("Submit");
        b_newac_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_newac_submitActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(b_newac_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(t_newac_day, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(c_newac_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(t_newac_year, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(t_newac_installedby, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_newac_brand, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_newac_block, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_newac_floor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_newac_room, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t_newac_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_newac_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_newac_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_newac_installedby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_newac_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_newac_block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_newac_floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t_newac_room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_newac_submit)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_newac_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_newac_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_newac_dayActionPerformed

    private void t_newac_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_newac_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_newac_brandActionPerformed

    private void b_newac_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_newac_submitActionPerformed
        try{
        
        newac_day=Integer.parseInt(t_newac_day.getText());
        newac_year=Integer.parseInt(t_newac_year.getText());
        
        }
        catch(NumberFormatException e){
        System.out.println("Number daal chutiye ");
        
        }
        
        newac_month=c_newac_month.getSelectedItem().toString();
        
        newac_date=Integer.toString(newac_day)+"/"+newac_month+"/"+Integer.toString(newac_year);
        newac_installed_by=t_newac_installedby.getText();
        newac_brand=t_newac_brand.getText();
        newac_block=t_newac_block.getText();
        newac_floor=t_newac_floor.getText();
        newac_room=t_newac_room.getText();

    }//GEN-LAST:event_b_newac_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        t_newac_day.setText("");
        t_newac_year.setText("");
        t_newac_installedby.setText("");
        t_newac_brand.setText("");
        t_newac_block.setText("");
        t_newac_floor.setText("");
        t_newac_room.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_newac_submit;
    private javax.swing.JComboBox<String> c_newac_month;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField t_newac_block;
    private javax.swing.JTextField t_newac_brand;
    private javax.swing.JTextField t_newac_day;
    private javax.swing.JTextField t_newac_floor;
    private javax.swing.JTextField t_newac_installedby;
    private javax.swing.JTextField t_newac_room;
    private javax.swing.JTextField t_newac_year;
    // End of variables declaration//GEN-END:variables
}
